### ISSUE TITLE
how to scan dicom 

### ISSUE THREAD

**Issue by accidentul** [RiccardoBiondi/segmentation#3]
Hello Riccardo, how can i scan dicom images and get back the mask overlay on the dicom file

Thx, 
Andrei

**Comment by RiccardoBiondi** [comment]
Dear Andrei,

If I have well understood, you have a DICOM series (so a single exam from a single patient). To process this kind of file, you have to organize them into a folder and provide the path as input. The mask will be saved as .nii or .nrrd binary image saving as the DICOM series is not yet supported.

The syntax looks like this:

                   python -m CTLungSeg --input='path/to/folder'  --output='path/to/mask.nii'



let me know if it answers your question.



Best Regards

Riccardo

From: Ramboiu Andrei ***@***.***>
Sent: Tuesday, June 7, 2022 6:36 PM
To: RiccardoBiondi/segmentation ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RiccardoBiondi/segmentation] how to scan dicom (Issue #3)


Hello Riccardo, how can i scan dicom images and get back the mask overlay on the dicom file

Thx,
Andrei

**Comment by accidentul** [comment]
Hello, yes it works But it saves only the mask not the full scan with the mask overlay

**Comment by RiccardoBiondi** [comment]
Ok, I am sorry but this function is not yet implemented. It is able only to save the binary mask

**Comment by accidentul** [comment]
Thank you for the quick response


Andrei
