### ISSUE TITLE
how is the dicom scan need to be to train a on new data  

### ISSUE THREAD

**Issue by accidentul** [RiccardoBiondi/segmentation#4]
Can you provide a example of the training data. ? 

Thx, 
Andrei

**Comment by accidentul** [comment]
?

**Comment by RiccardoBiondi** [comment]
Dear Andrei, 
The important thing for the training data is that the scan contains a large amount of ground glass to ensure the balancing between the different classes (lung parenchyma, ground glass, etc.) in the k-means clustering. 
Good examples can be the two top images in the README.

**Comment by accidentul** [comment]
so, the scan must have a ROI segmentation over the original image or simple scans with a large amount of GG ?

**Comment by RiccardoBiondi** [comment]
No GG ROI is required. You have to apply the lung extraction on the training images and then perform the training. Youi can use the provided bash and powershell scripts to automate this procedure

**Comment by accidentul** [comment]
Thank you for the rapid answer
Andrei
