### ISSUE TITLE
How can i output  de result of a image based on label based on centroid 

### ISSUE THREAD

**Issue by accidentul** [RiccardoBiondi/segmentation#5]
Hi Riccardo how can i output  de result of a image based on label based on centroid 
I want to clasify the type of leasion GGO or CS or healthy lung 
Example image 0001.dcm get the GGO or healthy lung, i want to store the result for each image or a set o images if GGO or CS is detected

Thx, 
Andrei

**Comment by RiccardoBiondi** [comment]
Hi! 
The result of the whole processing is a nifti file containing a binary mask of GGO and CS /(voxel Gl 0-> No GGO, 1 -> GGO).  If you want to distinguish between healthy lung and lesion areas (GGO and CS), you can binarize the images resulting from the lung extraction step, obtaining a lung mask. Then you can subtract the identified lesion areas from this mask, obtaining a binary mask opf the healthy lung parenchyma. 
Let me know if it answers to your question,
Regards
Riccardo

**Comment by accidentul** [comment]
Hello
Thank you for all your help it's perfect
